### ISSUE TITLE
Feedback on stochastic2

### ISSUE THREAD

**Issue by kennethkilo** [tbjw/ILAUBC#10]
In reference to version ff6db3184a5ea5a5be847ba9ff37c6038c996bf1
Google Page Rank Example:
"Page C is the most important, with a rank of ~~0.558~~, and page B is the least important, with a rank of 0.1752."
Should be:
"Page C is the most important, with a rank of **0.3558**, and page B is the least important, with a rank of 0.1752."

**Comment by tbjw** [comment]
Thank you! This will be fixed in the next build.
