### ISSUE TITLE
Duplication of note within chapter 2.3

### ISSUE THREAD

**Issue by j-james** [tbjw/ILAUBC#11]
The note beginning with "This note describes a subtle point, which you can disregard on first reading" is duplicated [here](https://www.math.ubc.ca/~tbjw/ila/parametric-form.html). This only occurs within the interactive textbook, not the PDF. 

Interestingly, I only found this section once within this repository, so the issue probably has something to do with how the textbook is generated.

**Comment by tbjw** [comment]
Thank you. This seems to be due to a bug in how the book-writing software handles sub-sub-sections. The sub-sub-section (paragraph) entitled "Parametric forms in vector notation" will be promoted to a subsection in the next version, which fixes this problem.
