### ISSUE TITLE
There may be a mistake in an example

### ISSUE THREAD

**Issue by tbjw** [tbjw/ILAUBC#14]
The example in question is about ellipses and circles in the chapter on determinants and areas.

**Comment by endger0125** [comment]
agree; the function should be inverted

**Comment by tbjw** [comment]
I believe the book is correct. If (x,y) is a point on the ellipse, then ([2x−y]/2,[y+3x]/3) is a point where the sum of the squares of the coordinates is 1, i.e., it’s a point on the circle. Therefore what the book says is correct. T takes the ellipse to the unit circle.
