### ISSUE TITLE
Feedback on eigenvectors

### ISSUE THREAD

**Issue by endger0125** [tbjw/ILAUBC#16]
In reference to version cb7c9f392996d932576955e5d76257b1dd01d71f
<img width="658" alt="Screen Shot 2021-11-12 at 15 22 05" src="https://user-images.githubusercontent.com/93898036/141594690-01bab2e0-cc00-41f3-a84f-e6bbf6e8f44b.png">

the circled number should undoubtably be -1 instead of 1

**Comment by tbjw** [comment]
Thanks. This will be fixed in the next update.
