### ISSUE TITLE
Feedback on eigenvectors

### ISSUE THREAD

**Issue by endger0125** [tbjw/ILAUBC#17]
In reference to version 67f5ffc26476cb4938886148dccfbb82378d84e1
<img width="686" alt="Screen Shot 2021-11-16 at 19 15 22" src="https://user-images.githubusercontent.com/93898036/142128191-44abfc0f-9836-47b2-b34b-e0a9c647e160.png">
I guess the circled word should be eigenvalue?

**Comment by tbjw** [comment]
Yes. This will be fixed in the next update. Thank you!
