### ISSUE TITLE
Feedback on diagonalization

### ISSUE THREAD

**Issue by endger0125** [tbjw/ILAUBC#18]
In reference to version 67f5ffc26476cb4938886148dccfbb82378d84e1
<img width="653" alt="Screen Shot 2021-11-16 at 22 57 04" src="https://user-images.githubusercontent.com/93898036/142149594-e307cc2d-78d8-4aa8-98c4-9a73457bae49.png">
it should be eigenvectors

**Comment by tbjw** [comment]
Yes, thank you! This will be fixed in the next version.
