### ISSUE TITLE
Feedback on diagonalization

### ISSUE THREAD

**Issue by endger0125** [tbjw/ILAUBC#19]
In reference to version 67f5ffc26476cb4938886148dccfbb82378d84e1
<img width="640" alt="Screen Shot 2021-11-16 at 23 07 26" src="https://user-images.githubusercontent.com/93898036/142150766-75a2948b-45c3-42f7-8415-1fe11a67edc9.png">
maybe is better to write <-1, 1> instead of <1, -1>? Despite they're all true, but for me, <-1, 1> is easier to understand.

**Comment by tbjw** [comment]
I think the fact that <-1,1> is appreciably easier to understand is actually an argument for using the other one, since it forces you to think about null spaces more conceptually. This will stay as it is.
