### ISSUE TITLE
Feedback on complex-eigenvalues

### ISSUE THREAD

**Issue by nightoad** [tbjw/ILAUBC#20]
In reference to version 854a7ec5708270d6a1abe1584fadcdc56d241314
In chapter 6.5, in the subsection "Geometry of 2x2 matrices with a complex eigenvalue" there is an error in the boxed recipe titled "Recipe: a 2x2 matrix with a complex eigenvalue". The 3rd step says "Find a corresponding (complex) eigenvalue 
v using the trick", where it should say "Find a corresponding (complex) eigenvector v using the trick". This is very confusing.
![Screen Shot 2021-11-22 at 4 32 03 PM](https://user-images.githubusercontent.com/94877107/142954925-1fd790e6-5b18-42a8-baa8-26e8857c7f19.png)

**Comment by tbjw** [comment]
You're right. Thanks for pointing this out. This will be fixed in the next update.
