### ISSUE TITLE
Feedback on dds

### ISSUE THREAD

**Issue by endger0125** [tbjw/ILAUBC#21]
In reference to version 854a7ec5708270d6a1abe1584fadcdc56d241314
<img width="639" alt="Screen Shot 2021-11-24 at 19 57 03" src="https://user-images.githubusercontent.com/93898036/143377389-18ec2aa3-ef0e-41a9-a871-9babb8cb8754.png">
this should be plus

**Comment by tbjw** [comment]
Thanks. There are a few small mistakes in this example. I have fixed several.
