### ISSUE TITLE
Feedback on dds

### ISSUE THREAD

**Issue by endger0125** [tbjw/ILAUBC#22]
In reference to version 854a7ec5708270d6a1abe1584fadcdc56d241314
<img width="532" alt="Screen Shot 2021-11-24 at 20 01 16" src="https://user-images.githubusercontent.com/93898036/143377731-b67ca25e-9e45-41d6-ab34-a4c91107703a.png">
I think probably move the brackets to the outside would be better. Like (0.4/0.9)^n. Otherwise when calculating limits, both numerator and denominator are zero, which indeed confused me for a few seconds.

**Comment by tbjw** [comment]
I think I'll leave it the way it is, on balance. But thanks for the suggestion.
