### ISSUE TITLE
Feedback on dds

### ISSUE THREAD

**Issue by michaelfromyeg** [tbjw/ILAUBC#27]
In reference to version 854a7ec5708270d6a1abe1584fadcdc56d241314.

The 6.5 in the $m_t$ equation becomes a 7.5, though I don't think it should. See the images below for reference. Notice the jump in the value from equation (6.6.2) to the following number of midges equations below in image 1.

### Image 1

![image](https://user-images.githubusercontent.com/35978975/163896561-571abfaf-d6ee-4497-afba-75a87a326a62.png)

### Image 2

![image](https://user-images.githubusercontent.com/35978975/163896635-68bc0791-1602-4136-9b64-abe950adfd76.png)

The answer (I believe) is 1/5 either way (i.e., it doesn't change the limit), but it is a bit confusing.

**Comment by tbjw** [comment]
Thanks! This is now fixed.
