### ISSUE TITLE
Feedback on linear-independence

### ISSUE THREAD

**Issue by nomanland769** [tbjw/ILAUBC#28]
![0C72015B-F8B0-47F5-A759-ACE9B477497F](https://user-images.githubusercontent.com/83886406/169414057-9a9c2297-f6bf-4ea5-b829-1f908fac798a.jpeg)
In reference to version 854a7ec5708270d6a1abe1584fadcdc56d241314

**Comment by tbjw** [comment]
Fixed! Thanks!
