### ISSUE TITLE
Feedback on bases-as-coord-systems

### ISSUE THREAD

**Issue by nomanland769** [tbjw/ILAUBC#30]
In reference to version 854a7ec5708270d6a1abe1584fadcdc56d24131
<img width="714" alt="Screen Shot 2022-05-26 at 5 50 59 PM" src="https://user-images.githubusercontent.com/83886406/170606945-c998b37e-6a69-427b-9d31-f8b8d7612b58.png">

*It should be subtracting the second equation from the first equation instead of the other way around (subtracting the first equation from the second equation).

*Mistake at the last sentence. It should be it follows that c`<sub>i</sub> = c <sub>i</sub> 
for all i

**Comment by tbjw** [comment]
Thanks, both fixed.
