### ISSUE TITLE
Feedback on index2

### ISSUE THREAD

**Issue by jackpatrick889** [tbjw/ILAUBC#31]
In reference to version 854a7ec5708270d6a1abe1584fadcdc56d241314

Hi, in the section on Parametric form, subsection Parametric Forms in Vector Notation, there is an error. In the section using (u=1-s) I believe it should be (2u-3), not (u-3)

![error in textbook](https://user-images.githubusercontent.com/114887348/193481865-7d735753-add9-4417-94ad-806e2f915839.png)

Thank you

**Comment by tbjw** [comment]
Thanks. This will be fixed in the next upload.
