### ISSUE TITLE
Feedback on matrix-transformations

### ISSUE THREAD

**Issue by dylanlauzy** [tbjw/ILAUBC#32]
In reference to version 854a7ec5708270d6a1abe1584fadcdc56d241314, 

<img width="693" alt="image" src="https://user-images.githubusercontent.com/64353872/194724116-a2e3577e-28c3-4eb8-9380-aae954035380.png">

Not sure, but I think the line "If Ax has n rows, then Ax has m entries for any given vector x in R^n" is wrong. I think it should say "If Ax has **m** rows..."

This is from _4.1 Matrix Transformations > Matrix Transformations_

**Comment by tbjw** [comment]
That's right! Thanks! This will be fixed in the next upload.
