### ISSUE TITLE
Feedback on bases-as-coord-systems

### ISSUE THREAD

**Issue by bhmohit** [tbjw/ILAUBC#33]
In reference to version 72c30ee2d9dac467abd9b2180e0dfdcec5da2653
In the example: "A nonstandard coordinate system on R<sup>2</sup>" The B coordinates for v = [4;1] however, right after solving for the B coordinates for V, the following paragraph mentions that the B coordinates for v = [5;1].

**Comment by tbjw** [comment]
Thank you! This will be fixed in the next upload, whenever that happens.
