### ISSUE TITLE
Feedback on invertible-matrix-thm

### ISSUE THREAD

**Issue by dylanlauzy** [tbjw/ILAUBC#34]
In reference to version 72c30ee2d9dac467abd9b2180e0dfdcec5da2653

The last example of the chapter states: "Suppose that A is an n x n matrix such that Ax = b is inconsistent some vector b ..."

The sentence is missing some word ('for' or otherwise) between "inconsistent" and "some vector b"

<img width="629" alt="Screenshot 2022-10-25 at 10 11 31" src="https://user-images.githubusercontent.com/64353872/197838799-0833ab44-eb77-455b-951a-6e94fa4a2501.png">

**Comment by tbjw** [comment]
Thanks! This will be fixed in the next upload.
