### ISSUE TITLE
Feedback on determinants-definitions-properties

### ISSUE THREAD

**Issue by dylanlauzy** [tbjw/ILAUBC#37]
In reference to version 72c30ee2d9dac467abd9b2180e0dfdcec5da2653

In the proof below the definition of a transpose, there is a line that goes "First suppose that A is a row vector **an** B is a column vector..." where there should be "and" instead of "an"

<img width="702" alt="image" src="https://user-images.githubusercontent.com/64353872/198897931-25f28908-5f94-44a7-9a11-5a764c431d38.png">

**Comment by tbjw** [comment]
Thank you! Will be fixed in the next upload.
