### ISSUE TITLE
Feedback on determinants-definitions-properties

### ISSUE THREAD

**Issue by dylanlauzy** [tbjw/ILAUBC#38]
In reference to version 72c30ee2d9dac467abd9b2180e0dfdcec5da2653

I think in the proof of the multilinearity property of the determinant function, there is a error in which defining property of the determinant function is applied to prove T(cu) = cT(u).

<img width="584" alt="image" src="https://user-images.githubusercontent.com/64353872/198898459-bc31a9dc-f845-483e-b178-d319f7730ec6.png">

Instead of "By the first defining property...", it should say "by the **second** defining property..."

**Comment by tbjw** [comment]
Thank you! This will be fixed in the next upload.
