### ISSUE TITLE
Feedback on determinants-volumes

### ISSUE THREAD

**Issue by ofekzil** [tbjw/ILAUBC#40]
In reference to version 72c30ee2d9dac467abd9b2180e0dfdcec5da2653
In the definition below, x1, x2 and xn should be replaced with v1, v2, vn (or vice versa).
![textbookToFix](https://user-images.githubusercontent.com/104530488/199578806-1780253c-f38b-40b5-85f9-f7005890af65.PNG)

**Comment by tbjw** [comment]
Thank you! This will be fixed in the next upload.
