### ISSUE TITLE
Feedback on matrix-transformations

### ISSUE THREAD

**Issue by ramjayakumar21** [tbjw/ILAUBC#41]
In reference to version 72c30ee2d9dac467abd9b2180e0dfdcec5da2653

Near the end of the chapter it says:

`If A has n rows, then Ax has m entries for any vector x in R n ; this is why the codomain of T ( x )= Ax is R m .`

I think it should be if `If A has m rows, then ...`.

**Comment by tbjw** [comment]
This seems to be correct in the source material, which is strange, because it's wrong on the website.

**Comment by tbjw** [comment]
Maybe I already fixed it? Anyway, a new upload is coming. Let's check the text after that.

**Comment by tbjw** [comment]
This is now also correct on the website.
