### ISSUE TITLE
Feedback on complex-numbers

### ISSUE THREAD

**Issue by ofekzil** [tbjw/ILAUBC#42]
In reference to version 72c30ee2d9dac467abd9b2180e0dfdcec5da2653
The fraction (1+i)/(1+i) has a typo in the following equation, in the expression after the first equal sign (under Arithmetic of Complex Numbers subsection) :
![textbookToFix_2](https://user-images.githubusercontent.com/104530488/203147547-fd15007a-88e7-4bfb-ab16-f1e103e5c4ee.PNG)

**Comment by tbjw** [comment]
Thanks! This will be fixed soon.
