### ISSUE TITLE
Feedback on orthogonal-complements

### ISSUE THREAD

**Issue by dylanlauzy** [tbjw/ILAUBC#43]
In reference to version 72c30ee2d9dac467abd9b2180e0dfdcec5da2653

The first line of the proof for "The orthogonal complement of a column space" proposition has some slight mis-wordings.

The first line reads: "To justify the first equality, we need to show that a vector x
 is perpendicular to **the** all of the vectors in W if and only if it is perpendicular **only** to..."

I think both bolded words above ("the" and "only") aren't required.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/64353872/204062192-d77060ea-e5e9-4c91-88bf-02ea4bf293ff.png">

**Comment by tbjw** [comment]
Thanks! Will be fixed soon.
