### ISSUE TITLE
Feedback on projections

### ISSUE THREAD

**Issue by IJNAkashiAR** [tbjw/ILAUBC#45]
In reference to version 6568e748e6090ddf3bd9124109836d3f8ccf2a18

![Screenshot from 2022-12-15 00-39-14](https://user-images.githubusercontent.com/23568101/207812700-33c2df3d-3205-4716-80f4-be3f1bb4342c.png)

Hi, shouldn't this line be in R^3 and not R^2? 

Thanks

**Comment by tbjw** [comment]
Yes. Thank you. This will be fixed in the next update.
