### ISSUE TITLE
Feedback on spans

### ISSUE THREAD

**Issue by Jiramide** [tbjw/ILAUBC#46]
In reference to version 6568e748e6090ddf3bd9124109836d3f8ccf2a18

![image](https://user-images.githubusercontent.com/16442486/212201348-d8f85c19-0397-4317-bc85-f6e7e47d88dd.png)
The vector at the very bottom, `(-1, 2, -1)`, is missing a negative sign before the 2

**Comment by tbjw** [comment]
Yes, thank you! This will be fixed in the next update.
