### ISSUE TITLE
Feedback on rank-thm

### ISSUE THREAD

**Issue by Anson-Chan-HK** [tbjw/ILAUBC#48]
In reference to version 6568e748e6090ddf3bd9124109836d3f8ccf2a18

In a paragraph,
"The reader may have observed a relationship between the column space and the null space of a matrix. In this [example in Section 3.3](https://github.com/tbjw/ILAUBC/issues/new?title=Feedback%20on%20rank-thm&body=In%20reference%20to%20version%206568e748e6090ddf3bd9124109836d3f8ccf2a18), the column space and the null space of a 3×2 matrix are both lines, in R2 and R3, respectively: "

Tthe column space should be in R3 and Nul space should be in R2 (as opposed to the opposite)

**Comment by tbjw** [comment]
Yes, thank you! This will be fixed in the next update.
