### ISSUE TITLE
Feedback on link issues

### ISSUE THREAD

**Issue by lexnewgate** [tbjw/ILAUBC#49]
the pdf links are without personal prefix version
https://www.math.ubc.ca/~tbjw/ila/demos/spans.html?v1=1,2,6&v2=-1,-2,-1&target=8,16,3&range=20&camera=3,.5,1.5
When you click above link, it jump to personal prefix version 
https://personal.math.ubc.ca/~tbjw/ila/demos/spans.html 
the para in the http get are missing. So the demos are displayed without paras.

**Comment by tbjw** [comment]
Thanks for highlighting this. It should be fixed now!
