### ISSUE TITLE
Feedback on solution-sets

### ISSUE THREAD

**Issue by kobayashley** [tbjw/ILAUBC#5]
In reference to version dc20b82c5991a13130b1353891ff31e88840a25c

Solution to Example (The solution set is a plane):
"This vector equation is called the parametric vector form of the solution set ... this says that the solution set is the set of all linear combinations of [1;1;1] and [-2,0,1]" 

should be [1;1;0] and [-2,0,1]?

**Comment by tbjw** [comment]
Thanks! This will be fixed in the new version.
