### ISSUE TITLE
Feedback on complex-numbers

### ISSUE THREAD

**Issue by yifeng-huang-math** [tbjw/ILAUBC#50]
In reference to version 6568e748e6090ddf3bd9124109836d3f8ccf2a18

In the example for "division by a complex number", there are some misplaced parentheses.

**Comment by tbjw** [comment]
This is a very strange bug. I don't know what caused it. I hope it will be fixed in the next update.

**Comment by tbjw** [comment]
It seems to be fixed now. You may need to reload the page to see the fix.
