### ISSUE TITLE
Feedback on solution-sets

### ISSUE THREAD

**Issue by matthewauwasd** [tbjw/ILAUBC#51]
In reference to version d2fe009538a800309f07adf0f13e646c9e9186f2

In the Chapter 3.1 Titled "Solution Sets", under Inhomogeneous Systems, and under the example titled "Example (The solution set is a plane).", there seems to be a typo. The vector associated with x2, (1,1,0) is mistakenly changed to (1,1,1) later on in the example.

**Comment by tbjw** [comment]
I think this is fixed, but I don't remember fixing it.
