### ISSUE TITLE
Feedback on similarity

### ISSUE THREAD

**Issue by Candyzorua** [tbjw/ILAUBC#52]
In reference to version d2fe009538a800309f07adf0f13e646c9e9186f2
In the "Eigenvalues of Similar Matrices" section, there is a typo:

<img width="701" alt="image" src="https://github.com/tbjw/ILAUBC/assets/75513525/16b5a035-897c-4150-9d85-0bdeea8a01a6">

"so that Cv is an eigenvalue of A with eigenvalue λ" should be corrected to
"so that Cv is an eigenvector of A with eigenvalue λ"

**Comment by tbjw** [comment]
Thanks! This will be fixed in the next upload.
