### ISSUE TITLE
Feedback on solution-sets

### ISSUE THREAD

**Issue by OdyAsh** [tbjw/ILAUBC#56]
In reference to version 6a5dc33173d4d0cb2881830c1cbf15cb73624f27,

the [following note](https://personal.math.ubc.ca/~tbjw/ila/solution-sets.html#soln-sets-dim-inhom) accidentally refers to itself instead of the previous important note in that section:

![image](https://github.com/tbjw/ILAUBC/assets/66007637/2b4a2239-c93b-4daa-b5ab-855ed231ba4f)

(i.e., you can keep recursing on this note by repeatedly clicking on `important note` )

Therefore, given my understanding of the context, I think that `important note` hyperlink should be updated to be this note instead:

![image](https://github.com/tbjw/ILAUBC/assets/66007637/45b75ca3-16af-4b53-a5bd-a53e3d1d7e5f)

**Comment by tbjw** [comment]
I think this will be fixed in the next upload.
