### ISSUE TITLE
Feedback on solution-sets (suggestion)

### ISSUE THREAD

**Issue by OdyAsh** [tbjw/ILAUBC#57]
In reference to version 6a5dc33173d4d0cb2881830c1cbf15cb73624f27

I personally suggest converting the purple line (referenced by the blue arrow) to be blue instead of purple, and to change the matrix A (referenced by the dashed blue rectangle) to be colored in blue[*], since I've just realized that A is responsible for creating this initial column span shown by purple on the right (again, referenced by the blue arrow). I think this will make this deduction for new learners easier ^^:

![image](https://github.com/tbjw/ILAUBC/assets/66007637/019c5f1e-56ea-410e-8664-d6e729a800b2)

[*]: if this is not possible since the interactive graph is an iframe probably from another application, then maybe we can just color the letter "A" when referencing that matrix to blue.

Note: I know this graph is implemented in many examples, so implementing this suggestion is difficult. However, I think this color coding once could be sufficient just for students to connect the dots :]

page section url: [here](https://personal.math.ubc.ca/~tbjw/ila/solution-sets.html#bluebox-24).

**Comment by tbjw** [comment]
The text does say that the span of the columns of A is in violet. There is definitely a problem in starting matrix algebra where students equate matrices with the spans of their columns. I am cautious about making that equation easier.
