### ISSUE TITLE
Feedback on linear-independence (typo)

### ISSUE THREAD

**Issue by OdyAsh** [tbjw/ILAUBC#58]
In reference to version 6a5dc33173d4d0cb2881830c1cbf15cb73624f27

Technically, the question mark (highlighted in red) should actually be a comma, due to the wording of the sentence highlighted in blue (or purple xD):

![image](https://github.com/tbjw/ILAUBC/assets/66007637/1db6aacd-b373-4c47-93fa-d6c0d9121cf6)

source url: [here](https://personal.math.ubc.ca/~tbjw/ila/linear-independence.html#bluebox-25)

**Comment by tbjw** [comment]
Thanks! Will be fixed in the next update.
