### ISSUE TITLE
Feedback on linear-independence (typo)

### ISSUE THREAD

**Issue by OdyAsh** [tbjw/ILAUBC#59]
In reference to version 6a5dc33173d4d0cb2881830c1cbf15cb73624f27

I believe the highlighted `p` is a typo, and should be `k`, since `p` is not mentioned anywhere else in the proof, while `k` is:

![image](https://github.com/tbjw/ILAUBC/assets/66007637/6327f812-4ff6-4176-bc6d-4453b6835107)

source url: [here](https://personal.math.ubc.ca/~tbjw/ila/linear-independence.html#linindep-facts)

**Comment by tbjw** [comment]
Thanks! That will be fixed in the next upload.
