### ISSUE TITLE
Feedback on eigenvectors

### ISSUE THREAD

**Issue by shubhbhalla** [tbjw/ILAUBC#6]
In reference to version dc20b82c5991a13130b1353891ff31e88840a25c

<img width="1440" alt="Screen Shot 2020-12-18 at 5 34 01 PM" src="https://user-images.githubusercontent.com/67706402/102612750-4de8e180-4157-11eb-9786-beabef746142.png">

I have attached a screenshot of the problem(highlighted). The highlighted text is incorrect as λ is not an Eigen vector.

**Comment by tbjw** [comment]
Thanks! Fixed in the new update.
