### ISSUE TITLE
Feedback on linear-independence (typo/confusing-wording)

### ISSUE THREAD

**Issue by OdyAsh** [tbjw/ILAUBC#60]
In reference to version 6a5dc33173d4d0cb2881830c1cbf15cb73624f27

I believe the word `can` underlined in red should be `can't`, since the theorem isn't true here, so it's technically not applied:

![image](https://github.com/tbjw/ILAUBC/assets/66007637/c3321127-b867-4884-8281-51320809eb10)

Same goes for the examples below it which don't apply the thoerem.

Source url: [here](https://personal.math.ubc.ca/~tbjw/ila/linear-independence.html#ul-21)

**Comment by tbjw** [comment]
The theorem is an if-and-only-if statement. One direction of the theorem is applied.
