### ISSUE TITLE
Feedback on linear-independence (suggestion)

### ISSUE THREAD

**Issue by OdyAsh** [tbjw/ILAUBC#61]
In reference to version 6a5dc33173d4d0cb2881830c1cbf15cb73624f27

I suggest hyperlinking the highlighted `row-equivalent matrices` here:

![image](https://github.com/tbjw/ILAUBC/assets/66007637/480d73fa-9b6c-4c51-873e-7a39ef445164)

To refer to the definition mentioned in section 3.2:

![image](https://github.com/tbjw/ILAUBC/assets/66007637/cf46d45c-d2b1-42e6-92ff-09678ef22d50)

url 1: [here](https://personal.math.ubc.ca/~tbjw/ila/linear-independence.html#linindep-pivot-cols)

url 2: [here](https://personal.math.ubc.ca/~tbjw/ila/row-reduction.html#p-149)

**Comment by tbjw** [comment]
Should be done in next update.
