### ISSUE TITLE
Feedback on matrix-transformations (typo)

### ISSUE THREAD

**Issue by OdyAsh** [tbjw/ILAUBC#62]
In reference to version 6a5dc33173d4d0cb2881830c1cbf15cb73624f27

Given what's highlighted in green, I think what's highlighted in red should be "m" not "n":

![image](https://github.com/tbjw/ILAUBC/assets/66007637/47f1b177-cb24-4367-beb3-0c067690368e)

Source url: [here](https://personal.math.ubc.ca/~tbjw/ila/matrix-transformations.html#definition-27)

**Comment by tbjw** [comment]
This is correct. The notation means the set of things T(x) where x is allowed to be any element of R^n.
