### ISSUE TITLE
Typo in section 4.2 

### ISSUE THREAD

**Issue by cml36252** [tbjw/ILAUBC#64]
<img width="690" alt="Screenshot 2024-04-11 at 2 19 45 AM" src="https://github.com/tbjw/ILAUBC/assets/104222290/a1b88829-f4f1-4a86-9f6c-1dd26050e8fa">

**Comment by tbjw** [comment]
I am just reading these now. Can you tell me what the typo is?

**Comment by cml36252** [comment]
The sentence at the bottom should say "in the adjugate matrix", where it just says "goes the adjugate". A little nitpicky, but wanted to point it out. You have done an awesome job on the textbook, probably the best I have used for any class. Thank you!

**Comment by tbjw** [comment]
Thanks! Will be fixed in the next upload.
