### ISSUE TITLE
Error in (3.1 solution sets) (example in inhomogenous - example (the solution set is a plane))

### ISSUE THREAD

**Issue by Sethu645** [tbjw/ILAUBC#65]
In reference to version 6a5dc33173d4d0cb2881830c1cbf15cb73624f27

Professor,

I guess the span for that example should be {(1, 1, 0),(-2,0,1)} + (1, 0, 0). But it is written as  {(1, 1, 1),(-2,0,1)} + (1, 0, 0)
<img width="665" alt="Screenshot 2024-04-12 at 3 13 24 PM" src="https://github.com/tbjw/ILAUBC/assets/124431209/148c3a92-2869-4f4d-9251-c1783c1a1521">

**Comment by tbjw** [comment]
Thanks! Will be fixed in the next upload.
