### ISSUE TITLE
Feedback on linear-independence

### ISSUE THREAD

**Issue by RandoNandoz** [tbjw/ILAUBC#66]
In reference to version 35d9402d4a50e271e215656a90448d4c9b8de6cc

For the proof to the theorem where $\set{v_1, v_2, \cdots, v_k}$ is linearly dependent iff. one of the vector is in the span of the other ones, there's a typo in the proof where subtract is spelled "subract".

<img width="736" alt="image" src="https://github.com/tbjw/ILAUBC/assets/30359448/da2f127f-ea17-4ce8-a84a-b48b645a88f6">

**Comment by tbjw** [comment]
Thanks! This should be fixed in the next upload!
