### ISSUE TITLE
Feedback on solution-sets

### ISSUE THREAD

**Issue by Ompatoom** [tbjw/ILAUBC#67]
In reference to version 35d9402d4a50e271e215656a90448d4c9b8de6cc

For the example (this solution set is a plane)
There is a mistake in this line 

"this says that the solution set is the set of all linear combinations of 
(1\\1\\1) and (-2\\0\\1)" 

(1\\1\\1) should be (1\\1\\0)

**Comment by tbjw** [comment]
Thanks! I think this will be fixed in the next upload.
