### ISSUE TITLE
Demo Clarification Section 4.2

### ISSUE THREAD

**Issue by cchamberlin2000** [tbjw/ILAUBC#68]
In reference to version 35d9402d4a50e271e215656a90448d4c9b8de6cc

The text acompanying second to last demo (within the second to last example) requires clarification. I had to set the control to homogeneous in order for the violet line to represent the null space.

**Comment by tbjw** [comment]
Thanks! This should be fixed in the next upload.

**Comment by cchamberlin2000** [comment]
You're welcome. Glad to help.

Craig Chamberlin
Math Department Chair
Palomar College
760.744.1150  x3276
