### ISSUE TITLE
Feedback on linear-transformations

### ISSUE THREAD

**Issue by Dan553594** [tbjw/ILAUBC#70]
IN Fact4.3.12 Multiplying a matrix by the standard coordinate vectors, the m×n matrix should has column from v1 to vn inside of v1 to vm.

In reference to version 35d9402d4a50e271e215656a90448d4c9b8de6cc
<img width="661" alt="Screenshot 2024-07-14 at 9 04 15 AM" src="https://github.com/user-attachments/assets/5e8bb325-8885-4866-92ac-cc46537bf47e">

**Comment by tbjw** [comment]
Thanks! This will be fixed in the next upload.
