### ISSUE TITLE
possible error on example (the solution set is a plane)

### ISSUE THREAD

**Issue by lumsdenbrady** [tbjw/ILAUBC#73]
In reference to version 35d9402d4a50e271e215656a90448d4c9b8de6cc 
![image](https://github.com/user-attachments/assets/5cf43a0b-fe22-499a-a6e9-5a50ae757150)
It appears that the spot saying the set of all linear combinations of (1,1,1) and (-2,0,1) should actually say (1,1,0) for the first vector

**Comment by tbjw** [comment]
Thanks! This should be fixed in the next upload.
