### ISSUE TITLE
Feedback on invertible-matrix-thm

### ISSUE THREAD

**Issue by AndreiSva** [tbjw/ILAUBC#79]
In reference to version ff6db3184a5ea5a5be847ba9ff37c6038c996bf1

![image](https://github.com/user-attachments/assets/3253840c-bc78-44b3-bbc4-547c67cadb23)

I think there is a typo in the last example on the page. Specifically, I believe it should say "Ax = b is inconsistent **for**  some vector b," instead of "Ax = b is inconsistent some vector b." The latter doesn't make grammatical sense to me.

**Comment by tbjw** [comment]
This should be fixed in the next update, I hope

**Comment by AndreiSva** [comment]
Looks like this is fixed now.
