### ISSUE TITLE
Feedback on row-reduction: contradiction

### ISSUE THREAD

**Issue by awhayat** [tbjw/ILAUBC#8]
In reference to version 47bbaba2866831267054877e3547ed974a4430fd

"Theorem: Every matrix is row equivalent to **one and only one matrix** in reduced row echelon form."

"We will give an algorithm, called row reduction or Gaussian elimination, which demonstrates that every matrix is row equivalent to **at least one matrix** in reduced row echelon form."

**Comment by tbjw** [comment]
This is correct as written. The text does not prove the full strength of the theorem.
