### ISSUE TITLE
Feedback on determinants-cofactors

### ISSUE THREAD

**Issue by yood2** [tbjw/ILAUBC#80]
Potential spelling mistake: "The determinant of a 3×3 matrix We can also use cofactor expansions to find a formula for the determinant of a 3×3 matrix. Let `is` compute the determinant of..."

<img width="743" alt="image" src="https://github.com/user-attachments/assets/3d14768b-a2cd-4e70-94fa-c336c220bda7">

In reference to version 97d3272cf06d584647ab34c01a72e1f899bccfaa

**Comment by tbjw** [comment]
This will be fixed in the next upload.
