### ISSUE TITLE
Feedback on dot-product Section 7.1

### ISSUE THREAD

**Issue by cchamberlin2000** [tbjw/ILAUBC#81]
In reference to version 97d3272cf06d584647ab34c01a72e1f899bccfaa

Under properties of the dot product, the third one listed is called "Distributivity with scalar multiplication," but it looks like associativity to me.

**Comment by tbjw** [comment]
This is interesting. You're right that the property is not distributivity, but it's also not associativity since in c(x • y) the two multiplications are not the same operation. It should be called "compatibility", and this will be changed in the next upload. Thanks!

**Comment by cchamberlin2000** [comment]
That's a good point. I guess some books call it the "scalar multiplication property" of the dot product. Either name sounds good.

Craig Chamberlin
Math Department Chair
Palomar College
760.744.1150  x3276
