### ISSUE TITLE
consusion on this line. "If  A  has  n  rows, then  Ax  has  m  entries for any vector  x  in  R n ;  this is why the codomain of  T ( x )= Ax  is  R m "Feedback on matrix-transformations

### ISSUE THREAD

**Issue by zjr-pjt** [tbjw/ILAUBC#9]
shoule it be m row instead of n rows?
In reference to version ff6db3184a5ea5a5be847ba9ff37c6038c996bf1

**Comment by tbjw** [comment]
This is correct as written. If A is an m x n matrix (m rows, n columns) and x is an n-vector (n rows) then Ax is an m-vector.
